### ISSUE TITLE
Add List Representation

### ISSUE THREAD

**Issue by kerberosmansour** [MichelleEmbleton/appSecRadar#14]
As a user of the radar I would like a list representation of the json/csv/txt content as well.

I would like this, because while the radar view is great to show the number of issues per segment, you can only view the details on at a time and it would be nice to have another representation under neath as well.

The lists should be by segment (e.g. services, platforms, etc..) or category (i.e. Hold, Adopt, etc..).

**Comment by MichelleEmbleton** [comment]
That's what I want to do next.
What do you think of the legend? Can you help with the text - to replace lorum ipsum...
I've added details on how to change the height to the Readme file.

**Comment by kerberosmansour** [comment]
@MichelleEmbleton Sounds good I'll take a look in a sec

**Comment by MichelleEmbleton** [comment]
Closing this, as done..
