### ISSUE TITLE
New Image

### ISSUE THREAD

**Issue by MichelleEmbleton** [MichelleEmbleton/appSecRadar#25]
![radar-7 1](https://user-images.githubusercontent.com/29818223/28792777-a4df10b6-7628-11e7-9654-971ccee32e0d.png)

**Comment by kerberosmansour** [comment]
Looks brilliant I would lower the plan for removal text a bit so it fits
but thats it

**Comment by MichelleEmbleton** [comment]
Great!
I'm working on click & drag to change radius's next.
You mean the 'Plan for Removal' red text at the top of the radar? They're all at a set measurement and that text is a bit longer than the others - but, yes, I'm sure I can make it look better...

**Comment by MichelleEmbleton** [comment]
New Image import..
![radar_7 21](https://user-images.githubusercontent.com/29818223/28841888-8f077bfe-76f3-11e7-9458-adc7fbae2d50.png)
